# Generated by Django 4.1.7 on 2023-04-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connection_id',
            field=models.BigIntegerField(auto_created=True, default=7378711868, unique=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='chat_room_id',
            field=models.BigIntegerField(auto_created=True, default=5652167558, unique=True),
        ),
    ]
