# Generated by Django 4.1.7 on 2023-04-15 00:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connection_id',
            field=models.BigIntegerField(auto_created=True, default=user.models.generate_connection_id, unique=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='chat_room_id',
            field=models.BigIntegerField(auto_created=True, default=user.models.generate_connection_id, unique=True),
        ),
    ]
